### ISSUE TITLE
지도 - 마커 클러스터화

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#101]
## 개요

마커 클러스터화 작업

<br>

### FE
- [x] 밀집되어 있는 마커를 하나의 마커로 클러스터화 한다.

![image](https://user-images.githubusercontent.com/44913775/205441830-ce78c01d-74b4-4ce9-86e0-6767fde8914c.png)

예시) 배달의 민족 포장 지도

### BE

<br>

## 비고

naver maps javascript api v3 에서 클러스터화 기능을 제공해주지 않습니다.

대신 비공식적으로, 마커 클러스터화가 구현되어있는 라이브러리를 `navermaps/marker-tools.js` [레포지토리](https://github.com/navermaps/marker-tools.js/blob/master/marker-clustering/src/MarkerClustering.js)에서 예제코드로 제공해줍니다.

이를 가져다 사용할 예정입니다.

\+ 마커 클러스터화 튜토리얼 : [링크](https://navermaps.github.io/maps.js.ncp/docs/tutorial-marker-cluster.example.html)

**Comment by CodeDiary18** [comment]
@jeong57281 예제 코드 사이트를 미리 보신게 있다면 issue 비고에 링크 첨부해주시면 좋을 것 같습니다!

**Comment by junghyunbak** [comment]
@CodeDiary18 첨부했습니다~

**Comment by YuriKwon** [comment]
@jeong57281 
최신 문서로 첨부하면 좋을 것 같습니다~~ 
https://navermaps.github.io/maps.js.ncp/docs/tutorial-marker-cluster.example.html

궁금한점이 있는데, 식당 카테고리와는 상관없이 클러스터링 하는거죠? 
그리고 클러스터링되는 경우 아이콘은 어떻게 나오나요? 숫자로 나오게 하실건가여?

**Comment by junghyunbak** [comment]
@YuriKwon 

1. 식당 카테고리마다 클러스터링 합니다
2. 일단 숫자로 구현해뒀는데 크기를 키우는 것도 가능할 것 같아요~ (사진에 배달의민족 예시처럼 일단 숫자로 구현할 생각이었습니다.)
3. 최신 문서 찾아와주셨네요... 제가 구글링 능력이 모자란가봐요

**Comment by YuriKwon** [comment]
@jeong57281 
1 -> 오 그럼 배달의 민족처럼 식당 아이콘 + 숫자로 나오는 건가요!? 완전 좋네요 
3 -> 제가 마커쪽 작업하면서 봤어서 그래요ㅎㅎ 구글링하면 예전 문서만 나오더라구요..

**Comment by YuriKwon** [comment]
이슈 작업대기로 옮겨 놓았습니다!!
