### ISSUE TITLE
식당 리스트 화면 - 모임장소 반경 내 음식점 확인

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#105]
## 개요

모임장소 반경 내 모든 음식점을 리스트로 렌더링한다.

<br>

### FE
- [x] 목록보기 버튼을 눌렀을 때 음식점 리스트 화면을 표시한다.
![image](https://user-images.githubusercontent.com/44913775/205543210-8d6ffd9c-651f-41df-b30f-66ebf689440d.png)

- [x] 음식점 리스트 화면에 모임장소 반경 내 모든 음식점을 렌더링한다.
![image](https://user-images.githubusercontent.com/44913775/205543318-6a208406-602e-4d25-8fa1-310afda79008.png)

- [x] 지도보기 버튼을 눌렀을 때 음식점 리스트 화면을 닫는다.
![image](https://user-images.githubusercontent.com/44913775/205543581-e536c01e-3ce7-4c21-b521-534e31a876d2.png)

### BE

<br>

## 비고

- 음식점 상세정보(thumbnail, rating)들의 제공은 현재(2022-12-05 12:35) 구현이 안되어 있기 때문에, 임의의 데이터를 사용한 후 추후에 반영 예정입니다.

- 투표 버튼은 다른 이슈에서 구현 될 예정이기 때문에 작동하지 않는 버튼으로 만들겠습니다.

**Comment by One-armed-boy** [comment]
확인이 완료되어 이동시켜놓겠습니다!
