### ISSUE TITLE
모임 자동 삭제

### ISSUE THREAD

**Issue by CodeDiary18** [boostcampwm-2022/web08-ChoBab#108]
## 개요
주기적으로 모임 삭제하는 로직 구현

<br>

### BE
- [x] Task Scheduling 조사
- [x] 주기적으로 모임 삭제하는 로직 구현
  - [x] roomStatic은 소프트 삭제
  - [x] roomDynamic은 완전 삭제(TTL 혹은 직접 삭제)
<br>

## 비고
- [Task Scheduling](https://docs.nestjs.com/techniques/task-scheduling) 조사 및 정리 후 모임 삭제 로직에 적용할 계획입니다.

**Comment by One-armed-boy** [comment]
MongoDB 자체에도 TTL 설정을 할 수는 있던데 그건 소프트 삭제가 아닌 완전 삭제 용일까요?

**Comment by CodeDiary18** [comment]
@One-armed-boy 
완전 삭제라고 알고 있습니다. 우선은 roomStatic은 소프트 삭제, roomDynamic은 완전 삭제(TTL 혹은 직접 삭제)로 설정하는 것으로 진행하려고 합니다!

**Comment by One-armed-boy** [comment]
아하 그렇다면 따로 스케줄러를 사용해야겠네요. 이해했습니다!
