### ISSUE TITLE
접속자 표시 - 접속자 마커 표시

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#117]
## 개요

![image](https://user-images.githubusercontent.com/44913775/205966177-5fc0d714-4b08-4a26-8760-b51b3ef6ea8b.png)

접속자의 위치를 받아와 지도위에 마커 생성

<br>

### FE
- [x] 접속자 위치정보를 이용해 지도 위에 마커 생성
- [x] 접속자마다 고유한 색상을 부여하여 접속자 리스트와, 마커 아이콘 색상에 반영

### BE

<br>

## 비고

[string-to-color](https://www.npmjs.com/package/string-to-color) 라이브러리를 이용해 세션 ID String 으로 고유한 색상을 얻어내어 구현 할 예정입니다.

**Comment by YuriKwon** [comment]
오.. 이런 라이브러리가 있나요? 신기하네요

**Comment by One-armed-boy** [comment]
옮겨두겠습니다.
