### ISSUE TITLE
클라이언트 측 API 요청 모듈 정리

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#123]
## 개요
현재 클라이언트 측에 무분별하게 작성된 API 요청 코드들을 한데 모아 하나의 모듈로 추상화하는 작업입니다.

<br>

### FE
- [x] 클라이언트 측에서 사용되는 fetch(axios) 요청 파악
- [x] 파악된 요청들을 추상화하여 하나의 모듈로써 /src/api에 생성
- [x] 요청 메서드 별로 추상화된 로직 작성
- [x] 메서드 별 로직들을 활용하여 API 별로 로직 작성
- [x] 전체 클라이언트 코드에 해당 모듈 적용

<br>

## 비고
{ 기타 내용, 의존성있는 작업 }

**Comment by YuriKwon** [comment]
@One-armed-boy 

개인적으로 utils 폴더보단 api 폴더를 하나 만들어서 그 안에
http 요청 메소드에 따라 공통적으로 쓰이는 로직을 하나 파고, 
각 도메인별로 쓰이는? api들을 모아놓으면 어떨까 합니다. 

https://github.com/woowacourse-teams/2020-taggle/tree/develop/frontend/src/api
 
여기처럼요! 
창명님은 이 방식에 대해 어떻게 생각하시나요~~

**Comment by One-armed-boy** [comment]
아 넵 저 때 유리님이 보여주셨던 방식 기억납니다! 비슷하게 진행할게요~
