### ISSUE TITLE
프론트엔드 환경설정 - 전체 폰트 적용

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#126]
## 개요

서비스에 어울리는 적절한 폰트를 찾아 일괄 적용

<br>

### FE
- [x] css 폰트를 적용하는 방법 학습
- [x] 프로젝트에 폰트 적용

### BE

<br>

**Comment by CodeDiary18** [comment]
@jeong57281 
작업 대기로 이동시키겠습니다.
