### ISSUE TITLE
식당 카테고리 - 카테고리 선택 및 필터링

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#130]
## 개요

헤더 아래에 있는 (식당 필터링에 사용되는) 카테고리 모달을 만드는 작업입니다.

(카테고리 영역을 이전에 창명님이 만들어두셔서 필터 모달을 토글하는 이슈는 따로 만들지 않고 바로 작업하려고 합니다.)

<br>

### 1) 카테고리 모달 컨트롤 바

- [x] 버튼을 누르면 열고 닫을 수 있는 카테고리 모달을 생성한다.
(Non-Modal 의 형태로 카테고리 이외의 영역을 눌러도 접히도록 구현한다.)
- [x] 선택된 카테고리에 맞게 안내 메세지가 변화한다. (`전체` - "먹고 싶은 음식을 선택해주세요!", `일부` - 현재 선택된 카테고리 정보 나열)

![Image](https://user-images.githubusercontent.com/44913775/206419140-92c712e0-5dc2-4dab-8030-013f4254d7bd.png)

### 2-1) 카테고리 모달 개요

- [x] 카테고리는 원하는 개수만큼 선택할 수 있으며, 누를 때 마다 식당 리스트와, 식당 마커가 필터링이 되어 다시 반영되도록 한다.

### 2-2) 카테고리 모달 내 버튼 상태

- [x] 카테고리 항목은 처음 서비스에 진입했을 때 `전체`로 선택되어있다.
- [x] 하나 이상의 카테고리가 선택되면 `전체`카테고리가 비활성화된다.
- [x] `전체`를 제외한 모든 카테고리가 선택되면 `전체` 카테고리가 활성화되고 나머지 카테고리는 모두 비활성화된다.
- [x] 카테고리가 하나도 선택되지 않으면 `전체` 카테고리가 활성화된다.

![Image](https://user-images.githubusercontent.com/44913775/206419208-60efb418-96a8-4539-8edb-aeff4a846320.png)

<br>

## 비고

- 사진에는 접속한 유저들의 카테고리 선택 정보가 나타나 있지만, P3 에 해당하는 다른 작업으로 이번 이슈에는 구현되지 않습니다.

- 카테고리 버튼을 누를 때 마다 지도마커와, 식당 목록이 영향을 받으므로 필요하다면 debounce 를  적용할 예정입니다.

**Comment by CodeDiary18** [comment]
디자인에서는 최소 2개 선택하라고 되어 있긴 한데 지금 진행된 프로젝트를 생각해 보면 최소 1개 이상 선택으로 해도 되지 않을까 싶습니다.
+) 추가로 1개 이상으로 진행된다면 (최소 1개)라는 텍스트는 빠져도 될 것 같습니다!

**Comment by YuriKwon** [comment]
전체 버튼 관련해서 생길 수 있는 여러 케이스에 대해 어떻게 처리할 지 조금 더 구체화되어야 할 것 같아요~!

ex) 전체 선택 상태에서 다른 카테고리 클릭 시 전체 버튼은 해제됨, 
여러 카테고리 선택 상태에서 전체 버튼 클릭 시 선택됐던 카테고리는 전부 해제됨

이런 내용이 조금 더 추가되어야 할 것 같습니다.

**Comment by junghyunbak** [comment]
@CodeDiary18 테크스펙을 더 상세하게 작성했습니다. 윤희님 말씀대로 "(최소 2개)" 문구는 빠져도 될 것 같습니다.

@YuriKwon 자세하게 다시 작성했습니다. 확인해주세요!
