### ISSUE TITLE
에러 페이지 생성

### ISSUE THREAD

**Issue by CodeDiary18** [boostcampwm-2022/web08-ChoBab#137]
## 개요
유효하지 않은 url 혹은 api 요청에 대한 처리(유효하지 않은 모임방, 그 외)를 위한 에러 페이지 생성

<br>

### FE
- [x] 에러 페이지 생성
- [x] 적용
  - [x] 유효하지 않은 url일 경우
  - [x] 모임방 참여에서 유효하지 않은 모임방이라는 응답이 오는 경우
  - [x] 그 외 api에서 Internal Server Error가 발생하는 경우

<br>

**Comment by junghyunbak** [comment]
중간에 서버 에러가 발생할 경우도 추가되어야 한다고 생각합니다. `500 Internal Server Error`

**Comment by CodeDiary18** [comment]
> 중간에 서버 에러가 발생할 경우도 추가되어야 한다고 생각합니다. `500 Internal Server Error`

@jeong57281 
저 부분이 nginx에서 문제 생겼을 때를 말하는 건가요? 아님 api 요청에 대한 응답으로 문제가 발생했을 경우를 말하는 건가요?

**Comment by junghyunbak** [comment]
@CodeDiary18

방 생성 요청, 방 유효성 검사 와 같은 부분에서 사용되는 api 의 500 에러와,
소켓 사용 중 오류라고 판단되는 부분에서

넘겨 줄 페이지가 필요하다고 생각했습니다.

NGINX 프록시가 오작동하면 그것도 서버 오류라고 볼 수 있겠죠? (결과적으로 클라이언트에게 오류로 돌아올테니...)

**Comment by CodeDiary18** [comment]
@jeong57281 
우선은 위에 작성된 경우에 대해서만 진행을 해보고 그 외의 상황에 대해서도 고민해보고 적용해봐도 괜찮을까요?

**Comment by junghyunbak** [comment]
@CodeDiary18

Not Found, 만료 방, 예상치 못한 에러(대표적인 예 - 500)

세 가지면 충분할 것 같습니다.

일단 체크리스트에 있으니, 옮겨놓겠습니다.
