### ISSUE TITLE
initRoom 페이지 내에서 시작하기 버튼을 클릭 후에도 추가적으로 클릭이 가능하던 버그 수정

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#138]
## 개요
initRoom 페이지에서 시작하기 버튼을 클릭 시, 서버 측에서 방을 생성하는 로직이 완료될 때까지 initRoom 페이지가 방치되고 있습니다. 이것이 문제가 되는 지점은, 시작하기를 누른 뒤 동일 버튼을 여러번 클릭 시 클릭한 횟수만큼 새롭게 방을 생성하는 요청이 서버로 들어가고 있습니다. 따라서 이에 대해 시작하기 버튼을 클릭 후에는 시작하기 버튼의 텍스트를 '모임 생성중....' 으로 수정하고 버튼을 클릭하지 못하도록 수정하는 작업이 요구됩니다.

<br>

## 체크리스트
{ 작업 체크리스트 }
### FE
- [x] initRoom 페이지 내 isStartButtonClicked 상태 추가
- [x] isStartButtonClicked 상태가 true일 때는 버튼의 클릭이 작동하지 않도록 수정 및 버튼 텍스트 수정 (시작하기 -> 모임 생성 중...)

### BE
- [ ] 

<br>

## 비고
{ 기타 내용, 의존성있는 작업 }

**Comment by CodeDiary18** [comment]
@One-armed-boy 
작업 대기로 이동시켰습니다!
