### ISSUE TITLE
지도 - 마커 설명창 디자인

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#139]
## 개요

마커를 클릭했을 때 나타나는 설명창을 디자인합니다.

<br>

### FE
- [x] infoWindow 에 들어가는 content html string 을 수정해 디자인한다.

<br>

## 비고

JSX Element 가 아닌, html 형태를 띈 string 을 수정하여 디자인하므로 css modules 방식을 사용하여 스타일을 입혀 줄 생각입니다.
(여태 껏 css module 방식으로 구현해왔지만 다시 한번 언급함.)

**Comment by One-armed-boy** [comment]
템플릿 리터럴을 사용하신다는 말씀이시죠?

**Comment by junghyunbak** [comment]
@One-armed-boy 지금봤네요. 넵 그렇습니다
