### ISSUE TITLE
로딩 스피너 통일

### ISSUE THREAD

**Issue by YuriKwon** [boostcampwm-2022/web08-ChoBab#147]
## 개요
1. 현재 로딩 페이지의 디자인이 제대로 되어있지 않음
2. 지도의 로딩 스피너 또한 디자인 필요

이러한 이유로 로딩 스피너를 일괄 통일시키는 작업을 진행하고자 합니다.

<br>

### FE
- [x] `react-loader-spinner` 라이브러리 설치 ([npm > react-loader-spinner](https://www.npmjs.com/package/react-loader-spinner))
- [x] 지도 위의 로딩 스피너 교체
- [x] 로딩 페이지에 로딩 스피너 적용

### BE

<br>

## 비고
- 적용하려는 스피너
  - 후보 1: oval  [링크](https://mhnpd.github.io/react-loader-spinner/docs/components/oval)
  - 후보 2: tail-spin  [링크](https://mhnpd.github.io/react-loader-spinner/docs/components/tail-spin)
- 회색 oval 형태 또는 tail-spin 형태 스피너로 적용하려고 합니다.  
  어떤 디자인이 더 나은지 댓글로 투표해주세요~~

**Comment by YuriKwon** [comment]
1번 oval -> 👍🏻 이모지
2번 tail-spin -> 👎🏻 이모지

**Comment by One-armed-boy** [comment]
옮겨 두겠습니다~
