### ISSUE TITLE
모임 생성 - 지도 드래그 이동 & 중앙 위치 받아오기

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#15]
## 개요
지도 드래그 이동할 때마다 중심 위치 받아오기

<br>

### FE
- [x] 지도 드래그 이동할 때마다 중심 위치 받기
- [x] 중심 위치 주소 화면에 렌더링

### BE

<br>

**Comment by One-armed-boy** [comment]
매 이동 시 중심 위치를 받으면 소요가 너무 크니까 디바운싱 적용 고려해도 좋을 것 같습니다!

**Comment by YuriKwon** [comment]
오~~ 좋은 의견 감사합니당ㅎㅎ

**Comment by junghyunbak** [comment]
확인했습니다. 이동시킬게요~ @YuriKwon
