### ISSUE TITLE
geolocation api 비동기 분리

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#154]
## 개요

geolocation의 느린 로딩시간을 기다리지 않도록 화면 생명주기를 변경합니다.

⚠️ 모바일 브라우저의 소켓 재접속 문제를 해결하기 위한, 소켓 생명주기 개편작업까지 추가로 진행 할 예정입니다. (2022-12-11 01:37 에 발견된 문제)

### 모바일 브라우저의 소켓 재접속 문제란?
모바일 환경에서 데이터 연결이 끊어지거나, 다른 화면으로 전환이 발생했을 때, 소켓 연결은 끊어지지만 화면은 unmount 되지 않고 살아있는 문제

<br>

### FE
- [x] #158
- [x] main 페이지의 geolocation 을 분리
- [x] 사용자의 위치 변화를 받아 실시간으로 반영하기 위한 이벤트 추가

### BE
- [x] main 페이지에서 사용자의 위치 변화를 받을 수 있는 이벤트 추가

<br>

**Comment by YuriKwon** [comment]
작업 대기로 이동해놓겠습니다~~
