### ISSUE TITLE
사용자의 접속이 끊어졌을 때 해당 사용자의 투표 기록을 전부 삭제하는 로직 추가

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#156]
## 개요
socket.gateway의 handleDisconnect 메서드 내에서 접속이 끊긴 사용자의 id와 방 코드를 감지하고 이를 통해 해당 사용자가 이전에 투표했었던 모든 기록을 삭제하는 처리 구현. 
또한 삭제된 기록을 모임 내 사용자들에게 다시 뿌려주는 로직까지 추가해야 함.

<br>

## 체크리스트
{ 작업 체크리스트 }
### FE
- [ ]

### BE
- [x] hadleDisconnect 내 접속이 끊긴 사용자의 투표 결과를 모두 삭제하는 로직 추가
- [x] 삭제된 투표 결과에 대해 다시한번 모임 내 사용자에게 뿌려주는 로직 작성

<br>

## 비고
{ 기타 내용, 의존성있는 작업 }

**Comment by junghyunbak** [comment]
확인완료햇습니다. 옮겨둘게요!
