### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by CodeDiary18** [boostcampwm-2022/web08-ChoBab#18]
## 개요
GitHub Actions를 이용한 CI/CD 구축

<br>

### CI
- [x] 빌드 테스트
- [x] 단위 테스트
- [x] eslint 테스트

### CD
- [x] 자동 배포 로직 작성
- [x] 프로젝트 repo에 Action Secrets 등록

<br>

## 비고
{ 기타 내용, 의존성있는 작업 }

**Comment by One-armed-boy** [comment]
@CodeDiary18 옮겨놓겠습니다!
