### ISSUE TITLE
API 응답 템플릿 설정

### ISSUE THREAD

**Issue by YuriKwon** [boostcampwm-2022/web08-ChoBab#32]
## 개요
API 응답이 일관된 형식으로 오도록 템플릿 설정하기

<br>

### BE
- [x] NestJS Interceptor 학습
- [x] Interceptor 이용하여 API Response 형식 맞추기
- [x] exception 템플릿 설정

<br>

**Comment by junghyunbak** [comment]
@YuriKwon 마지막으로 확인했습니다!

**Comment by YuriKwon** [comment]
@jeong57281 @One-armed-boy @CodeDiary18 
~~작업 진행중 질문사항이 생겨 공유드려요~~ -> 해결되었습니다!!

<br>

- 오전 회의에 새로 생긴 작업: 예외도 mapping 해주자.
- 이 작업에 대해 정확히 어떤 처리를 해줘야하는건지 얘기하지 않은 것 같아
  다시 얘기해봐야할 것 같습니다.

1. 인터셉터로 예외 잡아서 예외 변환하기
  : 에러를 일괄적으로 변환 -> 아마 필요없을 듯합니다.
- [관련 자료: wikidocs](https://wikidocs.net/158656)

2. Exception filtering
  : 예외 발생시 로그를 남기거나 응답 객체를 원하는 형태로 바꿀 수 있음
그러나 Nest Exception Layer에서 이미 기본적으로 response 타입을 다음과 같이 보내줌
```
{
  "statusCode": 500,
  "message": "Internal server error"
}
```
- [관련 자료: wikidocs](https://wikidocs.net/158651)
- [관련 자료: Exception Filter 블로그](https://velog.io/@junguksim/NestJS-%EB%85%B8%ED%8A%B8-1-Exception-Filters)

여기서 제가 추가로 작업해야하는게 어떤건지 모르겠어요..!
그리고 Exception Filter 쪽을 건드리게 된다면 추가 학습 시간이 필요할 것 같고
API 응답 템플릿 설정과는 결이 다른 것 같아 추가로 이슈를 생성해야할 듯 싶습니다.

**Comment by YuriKwon** [comment]
작업할 내용 (윤희님과 게더타운에서 미니 회의)

1. 로직에서 제어할 수 있는 에러는 customError로 처리
=> customError에 대한 응답 템플릿 필요
```
{"message": 에러 메시지}
```

2. 기본 에러도 동일한 형식으로 응답 
=> 기본 Error 반환값 변형 필요
```
{"message": 에러 메시지}
```
