### ISSUE TITLE
지도 - 지도에 음식점 마커 표시

### ISSUE THREAD

**Issue by YuriKwon** [boostcampwm-2022/web08-ChoBab#33]
## 개요
지도에 음식점 마커를 표시
1차적으로 기본적인 마커로 구현 후 음식점 카테고리에 따라 음식 모양 아이콘으로 변경할 예정

<br>

### FE
- [x] 지도에 음식점 마커 그리기
- [x] 카테고리에 따라 음식 모양 마커로 변경

<br>

## 비고
#41 작업 이후에 진행되어야 합니다.

**Comment by YuriKwon** [comment]
@jeong57281 시간되실 때 리뷰부탁드립니다!

**Comment by junghyunbak** [comment]
확인하고 작업 대기로 이동시켜두었습니다 @YuriKwon
