### ISSUE TITLE
DB 구축 및 연동

### ISSUE THREAD

**Issue by CodeDiary18** [boostcampwm-2022/web08-ChoBab#35]
## 개요
서버에 DB 구축 및 BE에 DB 연동

<br>

### DevOps
- [x] 서버에 DB 구축
  - [x] MongoDB
  - [x] Redis

### BE
- [x] DB 관련 연동 설정
  - [x] MongoDB
  - (Redis의 경우 #45 로 분리해서 설정)

<br>

## 비고
- 의존성있는 작업 
  - `PREV` : #34

**Comment by One-armed-boy** [comment]
테스트 서버, 프로덕션 서버 모두 레디스 설치 완료

**Comment by junghyunbak** [comment]
@CodeDiary18 마지막으로 확인 완료했습니다. 작업대기로 이동시킬게요~
