### ISSUE TITLE
지도 - 모임 반경 표시

### ISSUE THREAD

**Issue by CodeDiary18** [boostcampwm-2022/web08-ChoBab#38]
## 개요
모임 위치에 대한 위도, 경도 데이터를 받아 지도에 모임 반경 표시

<br>

### FE
- [x] 원으로 모임 위치 반경 표시
- [ ] 반경 밖은 불투명하게 처리
     ![Image](https://user-images.githubusercontent.com/74449232/202988934-c7ac806d-846c-494d-9974-23e87d8a209d.png)

<br>

## 비고
- 네이버 지도 API의 [Class: naver.maps.Circle](https://navermaps.github.io/maps.js.ncp/docs/naver.maps.Circle.html) 활용할 예정
  - [참고](https://navermaps.github.io/maps.js.ncp/docs/tutorial-1-shape-simple.example.html)
- 의존성있는 작업
  - `PREV`
    - 모임 위치 설정되어야 함
    - 모임에 참여하면서 모임 위치 데이터를 받아야 함

**Comment by junghyunbak** [comment]
@CodeDiary18 지난번에 슬랙에서 **모임 반경 표시** 작업 리뷰를 요청하셨고, 저도 확인했다고 말씀드렸는데요, 지금 보니깐 테크스펙이 좀 더 자세하게 작성되어야 할 것 같습니다.

"Naver Maps 의 어떤 Api 를 사용하여 구현할 것이다" 처럼 간략하게라도 적어주셨으면 합니다!

**Comment by CodeDiary18** [comment]
> @CodeDiary18 지난번에 슬랙에서 **모임 반경 표시** 작업 리뷰를 요청하셨고, 저도 확인했다고 말씀드렸는데요, 지금 보니깐 테크스펙이 좀 더 자세하게 작성되어야 할 것 같습니다.
> 
> "Naver Maps 의 어떤 Api 를 사용하여 구현할 것이다" 처럼 간략하게라도 적어주셨으면 합니다!

@jeong57281 비고에 말씀하신 부분 추가 반영했지만 구현시 변경될 수 있습니다!

**Comment by junghyunbak** [comment]
@CodeDiary18  확인했습니다!
