### ISSUE TITLE
모임 생성 - 방 생성 API

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#39]
## 개요
클라이언트 측에서 방 생성 요청이 서버로(/api/room) 전달되었을 때 방의 이름, 초대 링크 등을 반환하는 API 구축  

<br>

### BE
- [x] 방 생성 요청을 받은 뒤 요청 본문에서 위, 경도, 호스트의 식별자 파싱
- [x] 방 코드를 랜덤 문자열(uuid)로 생성
- [x] 방 코드 클라이언트에 반환

<br>

## 비고
- 테크 스펙
  - <a href="https://delicious-guys.notion.site/93d4fd3aa85d49a5b39bff7d50f706b8"> API 명세 </a>

- @CodeDiary18 로 작업 이관

**Comment by junghyunbak** [comment]
@One-armed-boy API 명세에 응답 상태코드는 빠져있는데, 아직 추가하지 않으신건가요?

**Comment by One-armed-boy** [comment]
@jeong57281 
- 정상적으로 생성 (200)

- 예외 처리 (400,500) 

같은 부분들 말씀하시는거죠??

**Comment by One-armed-boy** [comment]
아직 개발 전이라 어떤 예외 처리가 필요할지 와닿지가 않아서 해당 부분은 개발 후에 PR에서 상세하게 설명해도 될까요?

**Comment by junghyunbak** [comment]
@One-armed-boy 아 적절한 상태코드가 아니더라도, 당장 적을 수 있는 부분은 적어두는게 맞지 않을까요..? (예를 들면, 방 생성시에는 `201` Created, 실패 시 에는 `400` Bad Request 정도...?)

**Comment by One-armed-boy** [comment]
@jeong57281 일단 그러면 제가 좀 더 고민해보고 떠오르는 것들 위주로 명세 작성 하겠습니다. 개발하면서 떠오르는 부분들은 그때 그때 명세에 추가하고 PR에서 다시 공유드릴게요!

**Comment by One-armed-boy** [comment]
@jeong57281 추가했습니다! 확인하시고 승인 부탁드려요!

**Comment by junghyunbak** [comment]
@One-armed-boy  넵 확인했습니다! 작업대기로 이동시키겠습니다.

---

추가로, `403` 상태코드의 의미를 검색해보니

> 403 Forbidden은 서버가 허용하지 않는 **웹 페이지**나 **미디어**를 사용자가 요청할 때 웹 서버가 반환하는 HTTP 상태 코드이다.

라고 하네요. (Bold 처리한 경우에 해당할 때 내뱉는 상태코드 같아요)

잘못된 요청을 의미하는 `400` Bad Request 가 좀 더 적절해 보입니다!
