### ISSUE TITLE
Socket.io 설정 (server, client)

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#40]
## 개요

front, back Socket.io 설정

<br>

### BE

- [x] react socket.io-client 연동

### FE

- [x] Nest.js 와 Socket.io 연동

<br>

**Comment by CodeDiary18** [comment]
@jeong57281

**Comment by One-armed-boy** [comment]
@jeong57281 옮겨놓겠습니다!
