### ISSUE TITLE
모임 관리 - 확정된 모임 위치에 따른 식당 정보 불러오기

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#41]
## 개요
모임 위치의 위도, 경도, 반경 데이터를 이용하여 해당 범위의 음식점 데이터를 수집, 전처리, 반환하는 API 작성

<br>

## 체크리스트
{ 작업 체크리스트 }
### FE
- [ ]

### BE
- [x] kakao api key 등록
- [x] 클라이언트 요청 본문에서 모임 위치의 위도, 경도, 반경 정보, 방 제목을 파싱
- [x] API 를 활용하여 범위 내 모든 음식점을 가져옴
- [x] 가져온 음식점 정보를 우리 프로젝트에 맞는 형태로 전처리
- [x] 캐싱 DB에 방제목 - 음식점 데이터 리스트 구조로 저장(key-value)
- [x] 음식점 리스트 반환

<br>

## 비고
- 테크 스펙
  - <a href="https://delicious-guys.notion.site/8415521978974fc2a0ed6fa6a5e906e3">API 명세</a>
  - <a href="https://delicious-guys.notion.site/41-3c6a1c067d7e4f8e88b00d04731626dd">테크 스펙</a>
- 의문
  - 해당 api는 방 생성 시 딱 한번 사용되는 API 인건지?
    - 만약 방 생성 시 딱 한번 사용되는 API 라면 방 생성 로직에 포함시킬 수 있음.
    - 딱 한번 사용된다면 이후 모임 장소 변경은 고려하지 않아도 되는지?
  - 캐싱 흐름은 위 체크리스트의 흐름으로 가도 괜찮은지?
    - 이후 해당 방의 사용자가 필터링을 진행하면 필터 API를 통해 캐싱 DB의 데이터에 질의

**Comment by junghyunbak** [comment]
마지막으로 리뷰 완료하고 Projects 에서 작업 대기로 이동시켜뒀습니다. @One-armed-boy

**Comment by One-armed-boy** [comment]
카카오 api 를 만져보니 하나 문제점이, 한번의 질의로 가져올 수 있는 음식점 데이터 수의 제한이 걸려있습니다. (45곳)
그래서 이를 해결하기 위해 저희가 미리 어느정도 카테고리를 만들어 놓고, 이 카테고리를 가지고 검색을 진행하면 어떨까 합니다.
ex.
- 기존
  - 위,경도, 반경으로 음식점 검색 (최대 3번까지 api 호출 필요)
  - 가져올 수 있는 최대 음식점 갯수 (45곳)
- 제안
  - n개의 카테고리를 만들어 놓고(ex. 일식, 한식, 중식) 카테고리마다 따로 api 호출 
  - 위, 경도, 반경, 카테고리로 음식점 검색 (최대: 3*n 번의 api 호출 필요)
  - 가져올 수 있는 최대 음식점 갯수 (n * 45 곳)
