### ISSUE TITLE
모임 참여 - 방 유효성 검사 API

### ISSUE THREAD

**Issue by CodeDiary18** [boostcampwm-2022/web08-ChoBab#42]
## 개요
방 코드(roomCode)에 대해 유효성 검사하는 API 구현

<br>

### BE
- [x] 만료된 방인지 체크
- [x] 유효하지 않은 방인지 체크

<br>

## 비고
- [모임 방 유효성 검사 API 문서](https://delicious-guys.notion.site/ef1f24aedfdb45579a1b41125b7eab85)
- 의존성있는 작업
  - `PREV` : DB에 모임 방 정보가 있어야 함

- @One-armed-boy 로 작업 이관

**Comment by junghyunbak** [comment]
@CodeDiary18 확인했습니다. 작업대기로 옮겨놓겠습니다!
