### ISSUE TITLE
모임 관리 - 음식점 API 탐색 범위를 원형에서 사각형으로 변경

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#53]
## 개요
이후 캐싱을 위해 음식점 API 요청 범위를 원형에서 사각형으로 변경해야하는 소요 -> 카카오 로컬 API를 이용하여 구현 계획

<br>

## 체크리스트
{ 작업 체크리스트 }
### FE
- [ ]

### BE
- [ ] 반경(m) 데이터를 위, 경도 단위로 변환
- [ ] 위, 경도 단위로 변환된 반경을 이용하여 사각형 범위의 네 꼭짓점을 도출
- [ ] API 요청 및 결과 반환

<br>

## 비고
- DTO 윤희님 처럼 수정(validation 로직 작성)
- 인터페이스, 타입에 Type suffix 붙이기

**Comment by junghyunbak** [comment]
확인하고 작업 대기로 이동시키겠습니다 @One-armed-boy

**Comment by One-armed-boy** [comment]
외부 API 정책 상 영구적 캐싱이 불가능하기 때문에 해당 이슈 종료
