### ISSUE TITLE
타입스크립트 네이밍 통일

### ISSUE THREAD

**Issue by YuriKwon** [boostcampwm-2022/web08-ChoBab#56]
## 개요
11.24 오전 회의에 타입스크립트 Type/Interface 네이밍이 확정되면서, 
기존에 다른 형태로 작성되었던 코드들 일괄 수정이 필요합니다.

<br>

### 공통
- [x] suffix를 `Type`으로 변경
- [x] PascalCase로 변경

<br>

**Comment by One-armed-boy** [comment]
리뷰가 완료되어 작업대기로 이동시키겠습니다.
