### ISSUE TITLE
모임 참여 - 모임 입장 로직 작성

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#63]
## 개요
사용자가 
1. 모임 생성 - 시작하기 (호스트)
2. 초대 링크 접속
3. 모임 참여 버튼 -> 모임 코드 입력

세가지 방법으로 모임에 참여했을 때
메인 화면이 렌더링되는데 까지의 로직 작성

### 서비스 이용 흐름
1. 모임 생성 - 시작하기 (호스트)
- 모임 위치 설정 화면에서 시작하기 버튼 클릭
- /room/:{roomCode} 로 이동
- 로딩 (모임 검증 요청, 음식점 탐색을 위한 외부 API 요청이 완료될 때까지 대기)
- 메인 화면 렌더링

2. 초대 링크 접속
- 서비스 외부에서 domain/room/:{roomCode} 형식으로 http 요청을 수신
- 로딩 (모임 검증 요청,  음식점 불러오기를 위한 MongoDB 요청이 완료될 때까지 대기)
- 메인 화면 렌더링
 
3. 모임 참여 버튼 -> 모임 코드 입력
- 초기 화면에서 모임 참여 버튼 클릭
- roomCode 를 입력하는 입력창 노출(모달)
- /room/:{roomCode} 로 이동
- 로딩 (모임 검증 요청,  음식점 불러오기를 위한 MongoDB 요청이 완료될 때까지 대기)
- 메인 화면 렌더링

<br>

### FE
- [x] '모임 생성 - 시작하기', '초대 링크', '모임 참여' 세 기능을 이용한 사용자가 동일한 방에 입장할 수 있도록 로직 작성
- [x] 모임 생성, 음식점 탐색 요청 후 완료 시점 까지 로딩 화면 나타내기 
- [x] 상단바 렌더링
- [x]  지도 렌더링 
- [x] 모임 위치 마커 렌더링 
- [x] 유저 위치 마커 렌더링

### BE
- [x] 모임 접속 시 사용자를 MongoDB의 Room Dynamic에 추가
- [x] 모임 생성 시 불러온 음식점 데이터를 MongoDB의 Room Static에 적재하도록 로직 추가
- [x] 이미 생성된 모임에 접속 시 MongoDB Room Static을 통해 음식점 정보를 불러오도록 API 작성

<br>

**Comment by junghyunbak** [comment]
1, 3 방법으로 접속 시 `/room/:{모임코드}` 로 route 된 후, 메인화면에서 필요한 작업들을 마칠 때 까지 로딩화면을 띄워 놓는다.

와 같은 시나리오가 상세하게 작성되면 좋을 것 같습니다.

 \+ 같이 작업을 하기로 했지만 창명님이 쓰신 PR 이라 제가 함부로 수정하지는 않겠습니다.

**Comment by CodeDiary18** [comment]
@One-armed-boy 
#37 이슈의 상위 개념에서 더 구체적으로 작성되었다고 생각되는데 그렇다면 #37 이슈는 close 하거나 delete하는 건 어떨까요?

**Comment by One-armed-boy** [comment]
> @One-armed-boy #37 이슈의 상위 개념에서 더 구체적으로 작성되었다고 생각되는데 그렇다면 #37 이슈는 close 하거나 delete하는 건 어떨까요?

#37은 삭제하겠습니다

**Comment by YuriKwon** [comment]
정현님 의견에 동의합니다!!

**Comment by One-armed-boy** [comment]
@jeong57281 
@YuriKwon 

수정했습니다. 이 친구 덩치가 거의 공룡이네요.

**Comment by YuriKwon** [comment]
@One-armed-boy 

1. 모임 참여 페이지 생성도 별도 이슈로 추가하는게 좋을까요? 아님 이 이슈의 하위 작업일까요?!
2. 마스터 클래스 이후 소켓에 대해 얘기하다가 사용 여부에 대해 결론이 안났던거 같은데, 
  소켓을 그대로 사용할지, 다른 방법으로 실시간 통신을 구현할지 조사해오고 얘기해보는게 좋을까요?? 
3. `음식점 데이터를 MongoDB의 Room Dynamic에 적재하도록 로직 추가` 이 부분에 대해서.. 
  저번 오프라인 회의 때 Room Dynamic 안에 불러온 음식점 데이터를 안넣고 후보 음식점 데이터만 넣기로 했던 것 같은데 
  그러면 저 작업은 빠져도 되지 않을까요!?
4. 양이 엄청 많네요,, 고생하셨습니다!!

**Comment by One-armed-boy** [comment]
@YuriKwon 
@CodeDiary18 
@jeong57281 
(답변 내용이 좀 많아서 윤희님, 정현님도 태그합니다.) 

1. 이 부분은 사실 초기 화면에서 모달만 하나 띄워주려 했는데 이럼 추가적인 페이지 생성이 필요 없을 것 같아서 일단 해당 이슈에 포함시켰습니다.
2. 메인 화면 렌더링까지는 사실 소켓을 사용할 일이 없어서 소켓 연결 부분은 빼도 괜찮을 것 같습니다. (이 부분은 나머지 분들도 댓글 달아주세요)
3. 저 때 회의하면서 Room 에 넣기로 했었죠? (Room Dynamic 말고) 근데 그래도 지금 로직에는 외부 API로 가져온 데이터를 어디다 저장하는 로직이 없어서 비슷한 작업을 하긴해야할 것 같습니다. (만약 외부 API의 데이터를 어디에도 저장하지 않는다면 사용자가 모임에 참여할 때마다 새로 외부 API에 요청을 보내야하기 때문에...)
4. 그래도 정현님 계시니 힘닿는데 까지 해보고 안되면 다음주 할일로 미루겠습니다 ㅎㅎ. 사실 WBS에는 이 친구 1일로 잡혀있긴 한데 아예 잘못잡은거 같긴 해요

**Comment by YuriKwon** [comment]
2번 -> 그럼 주말에 소켓 말고도 실시간성을 구현할 수 있는 다른 방법들을 조사를 하긴 해야될까요??

3번 -> 제가 이해하기론 Room 컬렉션 없이 Room Static & Room Dynamic으로 가고, 식당 정보는 아예 저장하지 않는다! 였는데
  창명님 말씀은 Room Static에다가 저장하자! 인거죠!? 
  윤희, 정현님은 이 부분에 대해서 어떻게 이해하고 계셨나요!? (@CodeDiary18 @jeong57281)

4번 -> 1일이라니 정말 말도 안되네요...ㅋㅋ

**Comment by junghyunbak** [comment]
@One-armed-boy

* PR 메세지에 `1. 모임생성 - 로딩` 에 모임 생성 요청은 빠져야 할 것 같습니다! (모임 생성화면의 작업인 것 같습니다.)
> 메인 화면 렌더링까지는 사실 소켓을 사용할 일이 없어서 소켓 연결 부분은 빼도 괜찮을 것 같습니다. (이 부분은 나머지 분들도 댓글 달아주세요)

=> 일단은 소켓 사용여부가 정해지지 않았으니 일단 빼고 메인화면 렌더링을 구현하자는 이야기시죠?

---

@YuriKwon 

* 2번 소켓 사용 여부는 주말에 조사를 한번 해 보는게 좋을 것 같습니다.

* 3번 Room Static 에 저장하자.

> (만약 외부 API의 데이터를 어디에도 저장하지 않는다면 사용자가 모임에 참여할 때마다 새로 외부 API에 요청을 보내야하기 때문에...)

=> 창명님이 말씀하시는 것과 같이 생각합니다.

**Comment by CodeDiary18** [comment]
@One-armed-boy 
> 2. 메인 화면 렌더링까지는 사실 소켓을 사용할 일이 없어서 소켓 연결 부분은 빼도 괜찮을 것 같습니다. (이 부분은 나머지 분들도 댓글 달아주세요)

유효성 검사 API에 요청해서 유효한 방인지 아닌 지에 대한 응답을 받고 그에 대한 처리 로직은 미리 진행할 수 있을 것 같습니다!  

-----

@YuriKwon 
3번은 창명님과 동일한 의견입니다.
