### ISSUE TITLE
목록보기, 지도보기, 후보리스트 버튼

### ISSUE THREAD

**Issue by CodeDiary18** [boostcampwm-2022/web08-ChoBab#68]
## 개요
목록보기, 지도보기, 후보리스트 버튼 생성

<br>

### FE
- [x] 목록보기 버튼
     ![image](https://user-images.githubusercontent.com/74449232/204207915-740f1991-3de2-4628-b6d6-4370998ddaef.png)
- [x] 지도보기 버튼
   ![image](https://user-images.githubusercontent.com/74449232/204208135-318dda68-9eff-4b24-8fe1-7eaac1488baa.png)
- [x] 후보리스트 버튼
   ![image](https://user-images.githubusercontent.com/74449232/204208236-574793bf-7918-47c8-b4a9-c2fd76090ed9.png)

<br>

**Comment by YuriKwon** [comment]
작업 대기로 옮겨놓겠습니다.
