### ISSUE TITLE
Nginx 및 https 설정

### ISSUE THREAD

**Issue by CodeDiary18** [boostcampwm-2022/web08-ChoBab#69]
## 개요
배포 및 테스트 서버에 Nginx 및 https 설정하고 배포 서버에 도메인 연결

<br>

## 체크리스트
- 배포
  - [x] Nginx 설정
  - [x] https 설정
  - [x] 도메인 연결
- 테스트
  - [x] Nginx 설정
  - [x] https 설정
  - [x] release 서버에 서브 도메인(dev) 설정

<br>

## 비고
- 개발노트
  - [Nginx 설정](https://delicious-guys.notion.site/Nginx-https-e6a94c5b199242b9b49839331ff23e03)
  - [도메인 연결](https://delicious-guys.notion.site/db0fd5caa6d84047a270d138a43716b6)
  - [https 설정](https://delicious-guys.notion.site/https-d23a6d4be9e8408f85424e13b55db09e)

**Comment by One-armed-boy** [comment]
서브 도메인에 대한 의견을 정리해서 문서로 주시면 이를 읽고 리뷰 처리 하겠습니다!

**Comment by CodeDiary18** [comment]
@YuriKwon @One-armed-boy @jeong57281 
가비아에서 구매했던 도메인 연결과 Nginx 및 https 설정해두었습니다!
- prod 서버는 https://chobab.site 로 설정
- release(test) 서버는 dev 서브 도메인을 사용해 https://dev.chobab.site 로 설정
