### ISSUE TITLE
모임 참여 - 참여자 세션 생성

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#71]
## 개요

소켓에 접속한 모든 유저에게 세션 부여

<br />

### BE

- [x] Nest.js 소켓서버에 세션 미들웨어 연동하는 방법 조사
- [x] Nest.js 소켓서버에 세션 미들웨어 적용

<br />

## 비고

조사하고 학습한 뒤 적용하는 부분이라 자세한 테크 스펙은 작성 :x:

**Comment by CodeDiary18** [comment]
@jeong57281 학습과 적용을 체크리스트에서 따로 분리해도 좋을 것 같습니다!
