### ISSUE TITLE
식당리스트 화면 - 음식점 상세 정보 모달 이동 로직 및 API

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#73]
## 개요
식당리스트 화면에서 각 식당을 클릭 시 해당 음식점의 상세 정보 페이지로 이동하는 라우팅 구성

<br>

### FE
- ~~[ ] 식당 리스트 화면에서 index를 통해 식당의 식별자 추출~~
- ~~[ ] 식별자를 이용하여 params 를 통해 음식점 라우팅~~
- ~~[ ] 음식점을 클릭 시 해당 라우터로 이동하도록 이벤트 추가~~
- ~~[ ] 음식점을 클릭 시 해당 음식점 정보를 가져오기 위한 API 요청~~
- ~~[ ] 가져온 데이터를 통해 음식점 상세정보 모달(페이지 이동 x, 전체 페이지를 덮는 모달 형태로 구현) 렌더링~~

- 모달 형식으로 화면 구성의 논의가 되어(라우팅 불필요) FE 부분은 모두 #76 으로 이관합니다.

### BE
- [x] 음식점 상세 정보 외부 API 조사
- [x] 음식점 상세 정보 API 구현 (이미지, 영업정보, 평점 등의 데이터 추가로 필요.)

<br>

## 비고
- 식당 리스트 화면 구현이 선행되어야 함 
- 만약 이미지, 영업정보, 평점 등의 데이터를 가져올 수 없다면 간소화 예정
- <a href="https://www.notion.so/delicious-guys/API-e896040779244f0d850934ba9ada2e5f">API 명세</a>
- 추가
  - 이미지 관련 로직은 협의된 내용이 없기 때문에 우선 해당 이슈에서는 빼고 진행

**Comment by junghyunbak** [comment]
@One-armed-boy  `/room/{방 코드}/{식당 식별자}` 이렇게 중첩 라우팅을 해서 구현하시겠다는 건가요?

**Comment by One-armed-boy** [comment]
생각하신게 맞습니다! 그런데 사용될 API(현재 조사 중)에 따라 /restaurant/{식당 식별자} 로도 고려 중입니다.

**Comment by junghyunbak** [comment]
queryString, Params 사용하던, `room/:roomCode` 뒤에 추가로 라우팅이 되었으면 합니다.

queryString 을 사용하는 예 - `https://chobab.site/room/asvads-sfwee?page=DetailRestaurant&RestaurantCode=123`

**Comment by One-armed-boy** [comment]
@jeong57281 

이후 진행된 논의에 따라 화면 전체를 덮는 모달로 이를 구현하는 것으로 이슈를 수정해도 될까요??
(path의 변경 없음)

**Comment by junghyunbak** [comment]
@One-armed-boy 네 좋습니다.

**Comment by One-armed-boy** [comment]
넵 이슈 수정 후 팀원 분들께 다시 검토 받겠습니다.

**Comment by One-armed-boy** [comment]
@jeong57281 
@YuriKwon 
@CodeDiary18 

정현님과의 논의에 따라 이슈 수정했습니다. 한번더 확인 부탁드립니다! (이모지만 다시려면 이 댓글에 남겨주시면 됩니다.)

**Comment by YuriKwon** [comment]
1. 전체를 덮는 모달이라면 대충 배달의 민족의 이런 느낌인거겠죠..!?!?

<image width="300px" src="https://user-images.githubusercontent.com/55318618/204746058-1b614e07-7ba6-4c50-9c4f-bd9fb2bb69fd.png" />

2. 필수 기능까지는 아니겠지만, 상단에 이전 화면으로 돌아가는 버튼이 들어가면 좋을것같아요,, 
  나중에 시간 남으면 해보면 좋을듯합니다.

3. 음식점 상세페이지에서도 상단 헤더를 살려야할까요?  
  전 개인적으로 없어도 된다고 생각하긴 합니다. 저 공유 버튼은 오히려 식당 정보 공유로 헷갈릴거같아서..
<image width="300px" src="https://user-images.githubusercontent.com/55318618/204746886-47fd1fad-80a6-47e0-b0c5-c37a8b32ba68.png" />

**Comment by One-armed-boy** [comment]
@YuriKwon 

1. 맞습니다.
2, 3. 상단바에 뒤로가기 버튼 정도를 남기고 다 지우면 될까요?

**Comment by YuriKwon** [comment]
저는 그래도 좋을 것 같은데, 어떻게 생각하시나요!? 
내일 오전 회의때 다같이 얘기해 봐야 하려나요!

**Comment by One-armed-boy** [comment]
넵 좋습니다.
(그런데 생각해보니 음식점 상세 화면 구성 문제는 해당 이슈가 아닌 #76 에서 다루는게 맞는 것 같습니다.)

**Comment by YuriKwon** [comment]
오,,, 그러네요..ㅎㅎ
