### ISSUE TITLE
후보 식당 리스트 선택

### ISSUE THREAD

**Issue by CodeDiary18** [boostcampwm-2022/web08-ChoBab#74]
## 개요
후보 식당 리스트에서 특정 식당 선택시 식당의 상세 페이지로 이동하도록 컴포넌트 재사용

<br>

### FE
- [x] 후보 식당 클릭시 식당의 상세 페이지로 이동

<br>

## 비고
- 의존성있는 작업
  - `PREV`
    - 후보 식당 리스트 컴포넌트와 상세 정보 컴포넌트가 작업되어 있어야 합니다.

**Comment by junghyunbak** [comment]
확인했습니다. 이동시킬게요~
