### ISSUE TITLE
식당리스트 화면 - 후보 등록/취소 버튼 및 로직 구현

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#75]
## 개요
~~식당 리스트 화면 내 각 음식점에 후보 등록, 취소 버튼을 생성하고, 이를 서버와 연동하는 작업~~

<br>

## 체크리스트
{ 작업 체크리스트 }
### FE
- [ ] 식당 리스트 화면 내 음식점 후보 등록/취소 버튼 생성
- [ ] 식당 상세 화면 내 음식점 후보 등록/취소 버튼 생성

### BE
- [ ] 사용자들의 후보 선택 결과를 취합하여 MongoDB에 추가하는 로직 작성

<br>

## 비고
- 해당 작업은 소켓으로도 가능하고, 조금 로직을 틀면 단순 fetch로도 가능합니다.
- 소켓 이용
  - 사용자가 후보 등록/취소를 하면 그 즉시 소켓을 통해 이를 서버에 반영
  - 서버 측에서는 후보 등록된 횟수(만약 2명이 특정 음식점을 후보로 등록했다면 등록 횟수:2)로 관리
  - 후보 선택 단계가 끝나면 서버에서는 후보 등록 횟수가 1 이상인 음식점들을 roomDynamic: reserveList 에 추가
  - 장점
    - 로직이 직관적일 수 있다.(구현해봐야 알기는 함)
  - 단점
    - 사용자가 후보 등록/취소를 할 때마다 서버 측 DB에 접근해야한다. (소켓 소요 증가, DB 소요 증가)
    - 로직을 소켓에 의존해야한다.
- http 요청 이용
  - 사용자가 후보 등록/취소를 하면 이를 클라이언트 측 상태로 관리
  - 후보 선택 단계가 끝나면 서버 측에서 사용자들의 등록 현황을 가져와서 취합 후, 이를 roomDynamic: reserveList 에 추가
  - 장점
    - 소켓을 사용하지 않아도 된다.
    - 후보 선택 단계가 끝나고 이를 취합할 때 한번만 DB에 접근하면 된다.
  - 단점
    - 사용자들이 특정 시점에 일괄적으로 서버로 후보 등록 현황 정보를 보내는 추가적인 로직을 구성해야한다.

-> 소켓 사용으로 합의 및 단계 분리는 하지 않기로

**Comment by YuriKwon** [comment]
1. `reserveList`는 후보 식당보다는 예약 식당이라는 느낌이 드는 것 같습니다.
예약기능이 없긴 하지만, 약간 헷갈리네요..!

2. 후보 선택 단계가 끝난다는게 정확히 어떤 시점인가요?!
  저는 사용자가 후보 등록 버튼 누르자마자 후보 식당 리스트 데이터가 갱신된다고 생각했는데, 
  특정 시점에 한번에 업데이트되는걸까요?

**Comment by One-armed-boy** [comment]
1. 사실 투표를 위한 후보자의 의미는 candidate를 더 많이 쓰기는 한데 음식점에 이걸 붙이니깐 뭔가 이상하더라구요. 그래도 candidate가 나으려나요?

2. 이건 2주차에 오프라인(가배도) 회의 때 이야기가 나왔었던 거 같은데, 후보 음식점에 대한 등록/취소의 실시간 반영은 사용자들에게 혼란을 줄 수 있고 깔끔한 로직을 위해 단계를 나누자로 결론 났었던 걸로 기억해서 이렇게 적었습니다. (그 때 얘기 나왔던 가능한 혼란: 누군가 음식점을 후보에 등록했다가 갑자기 이를 뺐을 경우 사용자들의 투표가 의미 없어질 수도 -> 특정 순간이 되면 후보 음식점을 픽스하고 그에 대해 투표(좋아요)를 진행하자.)

**Comment by YuriKwon** [comment]
1. 개인적으론 candidate가 나은것 같습니다!!

2. 저 혼란 상황에 대해 말했던 것은 기억이 나는데,
  제가 기억하는 해결책은 1명 이상 투표했으면 후보 취소가 안되게 막자. 였던 것 같아요.
  내일 오전 회의에 다같이 얘기해보면 어떨까요? 
  만약 특정 순간에 픽스해야한다면, 그것과 관련해서 어떻게 처리할지 추가적인 얘기도 필요할 것 같습니다.

**Comment by YuriKwon** [comment]
후보 등록/취소 관련 로직이 투표로 바뀌면서, 이 이슈는 닫겠습니다. 
(80번에서 작업)
