### ISSUE TITLE
식당 상세정보 화면 - 식당 상세정보 화면 구성

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#76]
## 개요
선택된 식당의 상세정보를 불러오는 API를 작성하고, 이를 통해 음식점 상세정보 화면을 구성한다.

<br>

### FE
- [x] 식당 상세정보를 API를 통해 가져옴
  - [x] 식당 이미지
  - [x] 영업 정보
  - [x] 평점
- [x] 화면 구성
  - [x] 식당 이름
  - [x] 카테고리
  - [x] 식당 이미지
  - [ ] 영업 정보
  - [x] 전화번호
  - [x] 평점
  - [x] 주변 지도

### BE
- [x] 선택된 식당의 상세정보를 가져오는 API 작성

<br>

## 비고
식당 상세정보 페이지 내 추가로 들어가야할 내용인 식당 이름, 카테고리, 전화번호, 주변 지도 등은 이미 존재하는 정보이기 때문에 따로 추가하지 않겠습니다.

**Comment by CodeDiary18** [comment]
어떤 외부 API 활용할지는 확정되지 않았고 작업하면서 결정하는건가요?

**Comment by One-armed-boy** [comment]
해당 작업의 순위가 좀 후순위라 당장 API에 대한 조사는 아직 안이루어졌습니다. 해당 이슈에 대한 리뷰가 통과가되면 PR에서, 그렇지 않다면 이 이슈를 다룰 때 해당 이슈에서 다룰 것 같습니다.

**Comment by YuriKwon** [comment]
피그마에는 반영되어있지 않지만, 
영업 정보 하단에 지도도 들어가야합니다..!

**Comment by One-armed-boy** [comment]
지도 반영하겠습니다.

**Comment by junghyunbak** [comment]
마지막으로 확인했습니다.
