### ISSUE TITLE
후보 식당 화면 - 후보 식당 리스트 확인

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#77]
## 개요
후보 식당의 리스트를 확인할 수 있는 페이지 작성

<br>

## 체크리스트
{ 작업 체크리스트 }
### FE
- [x] 받은 후보 식당 정보들을 가지고 화면 구성
  - [x] 식당 이미지
  - [x] 식당 이름
  - [x] 좋아요 버튼
  - [x] 영업 정보
  - [x] 평점
  - [x] 모임 위치와의 거리
### BE
- [x] 후보 식당 정보를 서버를 통해 내려주는 로직 구현

<br>

## 비고
식당의 영업 정보, 평점 등의 데이터를 가져오는 것이 불가능할 수도 있고, 그 경우엔 해당 요소들은 제외시킬 예정입니다.

**Comment by junghyunbak** [comment]
확인했습니다. 작업 대기로 이동시키겠습니다.
