### ISSUE TITLE
공통 - 식당 투표 / 투표 취소 기능

### ISSUE THREAD

**Issue by One-armed-boy** [boostcampwm-2022/web08-ChoBab#80]
## 개요
식당을 투표하고, 취소할 수 있는 기능

<br>

### FE
- [ ] `투표`, `투표 취소` 기능 공통 컴포넌트 구현
- [ ] 식당 리스트 화면, 식당 상세 화면에 적용
- [ ] 식당 후보 리스트의 좋아요 컴포넌트 구현(내부적으로는 투표 기능과 같음)
- [ ]  식당 별 투표 현황 동기화 처리

### BE
- [ ] 식당 별 투표 현황을 `broadcast`하는 로직 작성 
  - [ ] `투표` 처리 로직
  - [ ] `투표 취소` 처리 로직

<br>

## 비고
- 처리 로직
좋아요 버튼 클릭 시 클라이언트 측 소켓 이벤트 발생 
-> 서버에서 이를 받아서 DB 최신화 
-> 서버 측에서 좋아요 동기화 이벤트(`broadcast`) 발생
-> 클라이언트에서 이를 받아서 좋아요 갯수 리렌더링

- 이벤트 이름은 맛있는 녀석들 notion > Socket event Docs 에 기록 예정

**Comment by junghyunbak** [comment]
확인했습니다. 작업 대기로 이동시키겠습니다.
