### ISSUE TITLE
후보 식당 화면 - 후보 식당 리스트 정렬

### ISSUE THREAD

**Issue by YuriKwon** [boostcampwm-2022/web08-ChoBab#82]
## 개요
slido ui로 리스트 정렬

<br>

### FE
- [ ] slido UI 구현방법 조사
- [ ] 유저가 좋아요 클릭시 ->  동적으로 정렬되도록 구현(framer-motion 라이브러리 적용)

### BE
- [ ] 

<br>

## 비고
#77 , #80 이 완료되어야 작업 가능

**Comment by junghyunbak** [comment]
@YuriKwon 

어떻게 슬라이도 UI 를 구현할 것인지에 대한 내용 `Tech Spec` 이 추가로 작성되었으면 좋겠습니다.

사실 저도 어떻게 구현해야 할 지 모르는 부분에 대해서는 이슈에다 "조사 후 구현" 와 같은 식으로 체크리스트를 작성하고, 팀원들의 ok 사인👍을 받아서 작업을 진행 한 적이 많은데, 반대로 제가 비슷한 이슈를 리뷰하려다 보니 저희가 예전에 거치기로 한 이슈 리뷰 단계 중 `Tech Spec` 검토 과정이 되고있지 않은 것 같다는 생각이 들었습니다. 🤔
