### ISSUE TITLE
접속자 표시 - 접속자 리스트 확인

### ISSUE THREAD

**Issue by junghyunbak** [boostcampwm-2022/web08-ChoBab#86]
## 개요

접속한 사용자 리스트를 on/off 하여 나오는 모달로 표시

<br>

### FE
- [x] 상단 좌측 탭에 사용자 접속 정보를 확인할 수 있는 모달을 토글할 수 있는 버튼 생성
![image](https://user-images.githubusercontent.com/44913775/204494535-57bc67db-43b8-45aa-91af-b95a32d57ab1.png)
- [x] 접속자 현황 모달에 실시간으로 사용자 입/퇴장을 반영

### BE
- [x] 소켓 이벤트에 입/퇴장을 알리는 로직 작성

<br>

**Comment by YuriKwon** [comment]
작업 대기로 옮겨놓겠습니다!!
